name: CSIT-1-Node-Test

on:
  push:
    branches:
      - '*'

jobs:
  csit:
    runs-on: ubuntu-latest

    services:
      opendaylight:
        image: ${{ vars.DOCKER_REPOSITORY }}/${{ vars.ODL_IMAGE_NAME_CENTOS }} 
        env:
          FEATURES: odl-restconf,odl-daexim-all,odl-netconf-topology,odl-jolokia
        ports:
          - 8181:8181
        options: --name odl-container

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Jolokia for AAA
        run: |
          docker exec -i odl-container bash -c \
          'echo "org.jolokia.authMode=basic" >> /home/user/karaf-0.18.1/etc/org.jolokia.osgi.cfg && \
          echo "org.jolokia.user=admin" >> /home/user/karaf-0.18.1/etc/org.jolokia.osgi.cfg && \
          echo "org.jolokia.password=admin" >> /home/user/karaf-0.18.1/etc/org.jolokia.osgi.cfg'

      - name: Use Reusable Workflow
        uses: ayushishu/releng-docker/.github/workflows/csit-1-node.yaml@main
        with: 
          docker_repository: ${{ vars.DOCKER_REPOSITORY }}
          robot_image: ${{ vars.ROBOT_IMAGE }}

      - name: Delay for 10 seconds
        run: sleep 10

      - name: Run AAA Test
        run: |
          docker exec robot bash -c "git clone https://github.com/opendaylight/integration-test.git &&
            cd integration-test/csit/suites/aaa &&
            robot -L debug --variable USER_HOME:/root \
              --variable WORKSPACE:/home/user \
              -v BUNDLEFOLDER:karaf-0.18.1 \
              -v ODL_STREAM:argon \
              --variable DEFAULT_LINUX_PROMPT:\\\$ \
              --variable ODL_SYSTEM_USER:user \
              --variable ODL_SYSTEM_IP:opendaylight \
              --variable ODL_SYSTEM_1_IP:opendaylight \
              -v IS_KARAF_APPL:True \
              authn"
