---
  name: CSIT-1-Node-Test
  
  on:
    push:
      branches:
        - '*'
  
  jobs:
    csit:
      runs-on: ubuntu-latest
      # Run the job on an Ubuntu latest runner
  
      services:
        opendaylight:
          image: ${{ vars.DOCKER_REPOSITORY }}/${{ vars.ODL_IMAGE_NAME_CENTOS }} 
          env:
            FEATURES: odl-restconf,odl-daexim-all,odl-netconf-topology,odl-jolokia
          ports:
            - 8181:8181
          options: --name odl-container
          # Set up a service container for OpenDaylight
  
      steps:
        - name: Checkout repository
          uses: actions/checkout@v3
          # Checkout the code repository
  
        - name: Setup Jolokia for AAA
          if: matrix.test_suite == 'aaa'
          run: |
            # Configure Jolokia for the 'aaa' test suite
            docker exec -i odl-container bash -c \
            'echo "org.jolokia.authMode=basic" >> /home/user/karaf-0.18.1/etc/org.jolokia.osgi.cfg && \
            echo "org.jolokia.user=admin" >> /home/user/karaf-0.18.1/etc/org.jolokia.osgi.cfg && \
            echo "org.jolokia.password=admin" >> /home/user/karaf-0.18.1/etc/org.jolokia.osgi.cfg'
   
        - name: Robot Setup    
          uses: ayushishu/releng-docker/.github/action/ssh-setup-action@ayush
          with: 
            docker_repository: ${{ vars.DOCKER_REPOSITORY }}
            robot_image: ${{ vars.ROBOT_IMAGE }}
        - name: Delay for 10 seconds
          run: sleep 10

        - name: Run Test
          uses: ayushishu/releng-docker/.github/action/robot-test-action@ayush
          with: 
            test_suite: aaa
